### ISSUE TITLE
Consider specifying `rule-empty-line-before`

### ISSUE THREAD

**Issue by jhancock532** [torchbox/stylelint-config-torchbox#22]
I'd recommend specifying this to improve code legibility. Consistent gaps between rules keeps them distinct, which is particularly useful when working with SCSS.

https://stylelint.io/user-guide/rules/list/rule-empty-line-before/

```
'rule-empty-line-before': ['always', { ignore: ['after-comment', 'first-nested'], except: ['first-nested'] }],
```

**Comment by thibaudcolas** [comment]
@jhancock532 as far as I can see we’re already enforcing this? This is what we have set up:

```js
"rule-empty-line-before": [
    "always-multi-line",
    {
      "except": [
        "first-nested",
      ],
      "ignore": [
        "after-comment",
      ],
    },
  ],
```

**Comment by thibaudcolas** [comment]
My bad, we do have this set up but only as of the upgrade to Stylelint v14 – hence why it wasn’t there before :) Closing.
